import { useState, useCallback } from "react";
import { useNavigate } from "react-router-dom";
import { ArrowLeft, RotateCcw } from "lucide-react";
import { Button } from "@/components/ui/button";
import { motion, AnimatePresence } from "framer-motion";

interface Round {
  id: number;
  question: string;
  optionA: string;
  optionB: string;
  aiOption: "A" | "B";
  explanation: string;
}

const rounds: Round[] = [
  {
    id: 1,
    question: "Which text was written by AI?",
    optionA: "The sunset painted the sky in hues of amber and crimson, casting long shadows across the meadow where wildflowers danced in the evening breeze.",
    optionB: "The sunset created a beautiful gradient of warm colors across the sky, with shades of orange and red blending seamlessly together, creating a visually stunning atmospheric phenomenon.",
    aiOption: "B",
    explanation: "AI text tends to be more descriptive and formulaic, using phrases like 'visually stunning atmospheric phenomenon' instead of natural imagery.",
  },
  {
    id: 2,
    question: "Which product review was generated by AI?",
    optionA: "Bought this blender last month. It's okay for smoothies but struggles with ice. The lid doesn't seal great — got spinach water on my ceiling lol. Would give 3.5 stars if I could.",
    optionB: "This blender is an exceptional kitchen appliance that delivers outstanding performance. The powerful motor handles all ingredients with ease, and the sleek design complements any modern kitchen aesthetic.",
    aiOption: "B",
    explanation: "AI reviews are often overly positive and generic, lacking the specific, personal anecdotes that real reviews contain.",
  },
  {
    id: 3,
    question: "Which email was drafted by AI?",
    optionA: "Hey Sarah — just checking in on the Q3 deck. I know you're swamped but the exec meeting is Thursday so if we could get a draft by EOD tomorrow that'd be awesome. Happy to jump on a quick call if that helps.",
    optionB: "I hope this email finds you well. I am writing to inquire about the status of the Q3 presentation deck. It would be greatly appreciated if you could provide an update at your earliest convenience.",
    aiOption: "B",
    explanation: "AI emails often use formal filler phrases like 'I hope this email finds you well' and 'at your earliest convenience' — hallmarks of generated text.",
  },
  {
    id: 4,
    question: "Which social media caption was AI-generated?",
    optionA: "Embracing the beauty of nature and finding inner peace through mindful exploration. Every journey begins with a single step, and today I chose to take that step towards a more balanced and harmonious life. 🌿✨ #Mindfulness #Nature",
    optionB: "finally touched grass after 3 weeks of debugging. 10/10 would recommend. the mass were slightly undercooked but vibes were immaculate 🌿",
    aiOption: "A",
    explanation: "AI captions are polished and inspirational but lack the humor, typos, and authentic voice of real social posts.",
  },
  {
    id: 5,
    question: "Which code comment was written by AI?",
    optionA: "// TODO: fix this hack before it bites us. works for now but will break if user has > 1000 items",
    optionB: "// This function implements a comprehensive data validation pipeline that ensures all input parameters conform to the expected schema before processing",
    aiOption: "B",
    explanation: "AI comments tend to be overly descriptive and formal. Real developer comments are terse, pragmatic, and sometimes include warnings about known issues.",
  },
];

const AISpotter = () => {
  const navigate = useNavigate();
  const [currentRound, setCurrentRound] = useState(0);
  const [selected, setSelected] = useState<"A" | "B" | null>(null);
  const [score, setScore] = useState(0);
  const [gameOver, setGameOver] = useState(false);

  const round = rounds[currentRound];

  const handleSelect = useCallback((option: "A" | "B") => {
    if (selected) return;
    setSelected(option);
    if (option === round.aiOption) {
      setScore((s) => s + 1);
    }
  }, [selected, round]);

  const handleNext = () => {
    if (currentRound + 1 >= rounds.length) {
      setGameOver(true);
    } else {
      setCurrentRound((r) => r + 1);
      setSelected(null);
    }
  };

  const restart = () => {
    setCurrentRound(0);
    setSelected(null);
    setScore(0);
    setGameOver(false);
  };

  return (
    <div className="min-h-screen bg-background">
      <header className="sticky top-0 z-40 h-14 flex items-center justify-between border-b border-border bg-card/80 backdrop-blur-sm px-4 md:px-6">
        <div className="flex items-center gap-3">
          <Button variant="ghost" size="icon" onClick={() => navigate("/mini-games")}>
            <ArrowLeft size={20} />
          </Button>
          <h1 className="text-lg font-bold text-foreground">🔍 AI Spotter</h1>
        </div>
        <span className="text-sm font-semibold text-muted-foreground">{currentRound + 1}/{rounds.length}</span>
      </header>

      <main className="max-w-2xl mx-auto p-4 md:p-8">
        {gameOver ? (
          <motion.div initial={{ scale: 0.9, opacity: 0 }} animate={{ scale: 1, opacity: 1 }} className="text-center py-12">
            <div className="text-6xl mb-4">{score >= 4 ? "🏆" : score >= 2 ? "👏" : "🤔"}</div>
            <h2 className="text-2xl font-bold text-foreground mb-2">Game Over!</h2>
            <p className="text-lg text-muted-foreground mb-1">You scored <span className="text-primary font-bold">{score}/{rounds.length}</span></p>
            <p className="text-sm text-muted-foreground mb-8">
              {score >= 4 ? "Amazing! You have a keen eye for AI content." : score >= 2 ? "Good job! Keep practicing." : "AI is tricky! Try again to improve."}
            </p>
            <div className="flex gap-3 justify-center">
              <Button variant="hero" onClick={restart} className="rounded-xl gap-2"><RotateCcw size={16} /> Play Again</Button>
              <Button variant="outline" onClick={() => navigate("/mini-games")} className="rounded-xl">Back to Games</Button>
            </div>
          </motion.div>
        ) : (
          <AnimatePresence mode="wait">
            <motion.div key={round.id} initial={{ opacity: 0, x: 30 }} animate={{ opacity: 1, x: 0 }} exit={{ opacity: 0, x: -30 }} transition={{ duration: 0.25 }}>
              <div className="mb-6">
                <h2 className="text-xl font-bold text-foreground mb-1">{round.question}</h2>
                <p className="text-sm text-muted-foreground">Tap the one you think was made by AI</p>
              </div>

              <div className="space-y-4">
                {(["A", "B"] as const).map((opt) => {
                  const text = opt === "A" ? round.optionA : round.optionB;
                  const isCorrect = opt === round.aiOption;
                  const isSelected = selected === opt;
                  let borderClass = "border-border hover:border-primary/40";
                  if (selected) {
                    if (isCorrect) borderClass = "border-green-500 bg-green-500/5";
                    else if (isSelected) borderClass = "border-destructive bg-destructive/5";
                    else borderClass = "border-border opacity-60";
                  }
                  return (
                    <div
                      key={opt}
                      onClick={() => handleSelect(opt)}
                      className={`relative p-5 rounded-2xl border-2 transition-all cursor-pointer ${borderClass}`}
                    >
                      <span className="absolute top-3 left-4 text-xs font-bold text-muted-foreground">Option {opt}</span>
                      <p className="text-sm text-foreground mt-4 leading-relaxed">{text}</p>
                      {selected && isCorrect && (
                        <span className="absolute top-3 right-4 text-xs font-bold text-green-600">✓ AI Generated</span>
                      )}
                      {selected && isSelected && !isCorrect && (
                        <span className="absolute top-3 right-4 text-xs font-bold text-destructive">✗ Human</span>
                      )}
                    </div>
                  );
                })}
              </div>

              {selected && (
                <motion.div initial={{ opacity: 0, y: 10 }} animate={{ opacity: 1, y: 0 }} className="mt-6">
                  <div className="bg-muted/50 rounded-xl p-4 mb-4">
                    <p className="text-sm font-semibold text-foreground mb-1">💡 Explanation</p>
                    <p className="text-sm text-muted-foreground">{round.explanation}</p>
                  </div>
                  <Button variant="hero" onClick={handleNext} className="w-full rounded-xl">
                    {currentRound + 1 >= rounds.length ? "See Results" : "Next Round →"}
                  </Button>
                </motion.div>
              )}
            </motion.div>
          </AnimatePresence>
        )}
      </main>
    </div>
  );
};

export default AISpotter;
